=== Machiavelli86/wba2ss13/Aufgabe1/src/Aufgabe3.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">


	<xsd:element name="collection" type="collection" />
	<xsd:element name="recipe" type="recipe" />
	<xsd:element name="title" type="xsd:string" />
	<xsd:element name="subtitle" type="xsd:string" />
	<xsd:element name="photos" type="photos_type" />
	<xsd:element name="photo" type="photo_type" /> 
	<xsd:element name="user" type="xsd:string" />
	<xsd:element name="address" type="xsd:anyURI" />
	<xsd:element name="portions" type="xsd:positiveInteger" />
	<xsd:element name="ingredients" type="ingredients" />
	<xsd:element name="ingredient" type="ingredient" />
	<xsd:element name="sort" type="xsd:string" />
	<xsd:element name="amount" type="amount" />
	<xsd:element name="unit" type="xsd:string" />
	<xsd:element name="time" type="time" />
	<xsd:element name="difficulty" type="difficulty" />
	<xsd:element name="nutrition" type="nutrition" />
	<xsd:element name="step" type="xsd:string" />
	<xsd:element name="comments" type="comments_type" />
	<xsd:element name="comment" type="comment_type" />
	<xsd:element name="author" type="xsd:string" />
	<xsd:element name="avatar" type="xsd:anyURI" />
	<xsd:element name="date" type="xsd:dateTime" />
	<xsd:element name="message" type="xsd:string" />

	<xsd:complexType name="collection">
		<xsd:sequence>
			<xsd:element ref="recipe" maxOccurs="unbounded" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="recipe">
		<xsd:sequence>
			<xsd:element ref="title" />
			<xsd:element ref="subtitle" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="photos" />
			<xsd:element ref="portions" />
			<xsd:element ref="ingredients" />
			<xsd:element ref="time" />
			<xsd:element ref="difficulty" />
			<xsd:element ref="nutrition" />
			<xsd:element ref="step" />
			<xsd:element ref="comment" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="photos_type">
		<xsd:sequence>
			<xsd:element ref="photo" maxOccurs="unbounded" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="photo_type">
		<xsd:sequence>
			<xsd:element ref="user" />
			<xsd:element ref="address" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ingredients">
		<xsd:sequence>
			<xsd:element ref="ingredient" maxOccurs="unbounded" minOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ingredient">
		<xsd:sequence>
			<xsd:element ref="sort" />
			<xsd:element ref="amount" minOccurs="0" maxOccurs="1" />
			<xsd:element ref="unit" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="time">
       	<xsd:simpleContent>
       		<xsd:extension base="xsd:float">
            	<xsd:attribute name="unit" type="xsd:string" use="required"/>
            </xsd:extension>
       	</xsd:simpleContent>
	</xsd:complexType>

	<xsd:simpleType name="difficulty">
      	<xsd:restriction base="xsd:string">
        	<xsd:enumeration value="easy"/>
        	<xsd:enumeration value="medium"/>
        	<xsd:enumeration value="hard"/>
     	 </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="nutrition">
       	<xsd:simpleContent>
       		<xsd:extension base="xsd:integer">
            	<xsd:attribute name="unit" type="xsd:string" />
            </xsd:extension>
       	</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="comment_type">
		<xsd:sequence>
			<xsd:element ref="comment" maxOccurs="unbounded" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="comments_type">
		<xsd:sequence>
			<xsd:element ref="author" />
			<xsd:element ref="avatar" />
			<xsd:element ref="date" />
			<xsd:element ref="message" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="amount">
      	<xsd:restriction base="xsd:decimal">
			<xsd:minExclusive value="0"/>
      	</xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== Machiavelli86/wba2ss13/Aufgabe1/src/Aufgabe32.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3.xsd">
  <recipe>
    <title>title</title>
    <photos/>
    <portions>1</portions>
    <ingredients>
      <ingredient>
        <sort>sort</sort>
      </ingredient>
    </ingredients>
    <time unit="">0</time>
    <difficulty>easy</difficulty>
    <nutrition unit="">0</nutrition>
    <step>step</step>
    <comment/>
  </recipe>
</collection>

=== Machiavelli86/wba2ss13/Aufgabe1/src/Aufgabe31.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3.xsd">
  <recipe>
    <title>title</title>
    <photos/>
    <portions>1</portions>
    <ingredients>
      <ingredient>
        <sort>sort</sort>
      </ingredient>
    </ingredients>
    <time unit="">0</time>
    <difficulty>easy</difficulty>
    <nutrition unit="kcal">0</nutrition>
    <step>step</step>
    <comment/>
</recipe>

<recipe>
    <title>title</title>
    <photos/>
    <portions>4</portions>
    <ingredients>
      <ingredient>
        <sort>Zucker</sort>
      </ingredient>
    </ingredients>
    <time unit="Std">2</time>
    <difficulty>medium</difficulty>
    <nutrition unit="kcal">456</nutrition>
    <step>step</step>
    <comment/>
  </recipe>


</collection>
